### PR TITLE
FEA: add RecVAE model

### PR DESCRIPTION
**Pull request by Sherry-XLL**

### CODE REVIEW

**Comment by deklanw** [comment]
@Sherry-XLL Nice work! I have a question though:

The RecVAE repo says

> Current model is slightly different from the one described in the paper, you can find original code here.

With a link to a different branch.

Which branch did you base your code on? Unfortunately the repo doesn't explain the differences explicitly. I'm curious if you figured it out while implementing it.

**Comment by Sherry-XLL** [comment]
@deklanw First of all, thank you very much for your attention to our code, which is based on the github link given in the paper at https://github.com/ilya-shenbin/RecVAE. 

As for the current model and the original code mentioned in the RecVAE repo, there is no essential difference between them. The paper’s description of the model implementation is based on the [original ipython notebook](https://github.com/ilya-shenbin/RecVAE/blob/wsdm/recvae.ipynb), which is convenient for debugging and outputting the paper results. In order to encapsulate the code into a complete project, the model in this [repo](https://github.com/ilya-shenbin/RecVAE) uses three classes including Encoder, CompositePrior and VAE to modularize the source code, and this is the reason why we use the code in this [repo](https://github.com/ilya-shenbin/RecVAE) as a reference.

**Comment by deklanw** [comment]
@Sherry-XLL I see, thanks. So it was just refactoring a notebook into cleaner modules? 

Idk how close to finished this PR is, but just looking through the code I've noticed a few things:

- In the original the encoder used residual connections in the encoder https://github.com/ilya-shenbin/RecVAE/blob/master/model.py#L72-L76 but I don't see that in this implementation.
- In the original the logvars and mus are produced from two separate Linear modules on the last hidden layer https://github.com/ilya-shenbin/RecVAE/blob/master/model.py#L77 but in this implementation there is a single Linear layer at the end and the logvars and mus are identical? That can't be correct https://github.com/Sherry-XLL/RecBole/blob/master/recbole/model/general_recommender/recvae.py#L117
- The original implementation alternates between training the encoder and decoder, with the encoder being trained more often and with a denoising component. See https://github.com/ilya-shenbin/RecVAE/blob/master/run.py#L161-L163 I don't see that in this implementation

**Comment by Sherry-XLL** [comment]
@deklanw
- As for the question 1, the encoder used 5-layer densely connected convolutional networks in the original code, and we will modify `Encoder` in the next commit.
- As for the question 2, although the logvars and mus are produced from two separate Linear modules, the two Linear modules are both `nn.Linear(hidden_dim, latent_dim)`, and there is no difference in the results of our model implementation.
- As for the question 3, it is our negligence that the current model does not have alternate training. We will add `RecVAETrainer` in `recbole.trainer.trainer.py` in the next commit.

Thank you very much for your attention and kindly corrections, we will improve the RecVAE code this week.

**Pull request merged**
