### PR TITLE
Documentation Improvement: Added examples for specific trainers

### PR DESCRIPTION
**Pull request by yarncraft**
Hello guys, when working with your library I stumbled upon the following error when I tried to run RecVae with the **basic Trainer**:

```python
 File ".../recbole/trainer/trainer.py", line 160, in _train_epoch
    losses = loss_func(interaction)
TypeError: calculate_loss() missing 1 required positional argument: 'encoder_flag'
```
 I went through your codebase to check whether I made a mistake and I saw that you had implemented custom trainers for a couple of models! With the custom RecVAETrainer this error was quickly resolved. Since this was missing in the docs I updated both the RecVAE and LightGBM model documentation and added a more elaborated example that should clear things up for future devs 😄 Thanks for the great library, I am a huge fan

### CODE REVIEW

**Comment by 2017pxy** [comment]
@yarncraft Hi, firstly thanks for your close attention to RecBole. 
About the trainer, indeed there are some custom trainers in RecBole. To help users load correct trainer, we have already implemented a function called `get_trainer` in [utils.py](https://github.com/RUCAIBox/RecBole/blob/master/recbole/utils/utils.py#L78-L96). So about this problem, my suggestion is using `get_trainer()` rather than import specific trainer by yourself.

BTW, the model can also be loaded automatically if you use the `get_model()` in [utils.py](https://github.com/RUCAIBox/RecBole/blob/master/recbole/utils/utils.py#L50-L75) rather than import specific model by yourself.

So, a more clear code can be:
```
import logging
from logging import getLogger

from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.utils import init_logger, get_model, get_trainer, init_seed
from recbole.utils.utils import set_color


if __name__ == '__main__':

    # configurations initialization
    config = Config(model='RecVAE', dataset='x', config_file_list='x.yaml')
    init_seed(config['seed'], config['reproducibility'])

    # logger initialization
    init_logger(config)
    logger = getLogger()

    logger.info(config)

    # dataset filtering
    dataset = create_dataset(config)
    logger.info(dataset)

    # dataset splitting
    train_data, valid_data, test_data = data_preparation(config, dataset)

    # model loading and initialization
    model = get_model(config['model'])(config, train_data).to(config['device'])
    logger.info(model)

    # trainer loading and initialization
    trainer = get_trainer(config['MODEL_TYPE'], config['model'])(config, model)

    # model training
    best_valid_score, best_valid_result = trainer.fit(
        train_data, valid_data, saved=saved, show_progress=config['show_progress']
    )

    # model evaluation
    test_result = trainer.evaluate(test_data)
    print(test_result)
    
```

**Comment by yarncraft** [comment]
@2017pxy Hi, thanks for the feedback, I was following your guide: https://recbole.io/docs/user_guide/usage/use_modules.html.
Maybe we should promote the use of `get_trainer()` and `get_model()` together with your example above in the _in-depth usage_ part of the quickstart? I was missing such an example in the Quickstart, given that I was working with a custom dataset.

I'm extensively using the general_recommender part of your library for my thesis research, and I could provide more documentation (feedback). Shall I do this in a Github issue or shall I provide this in a PR? 😃 

As for the `training_neg_sample_num=0` this was already included in my yaml config files 😄

**Comment by yarncraft** [comment]
Also, from a design perspective, the Furo theme looks a lot cleaner and has some interesting features such as the current-subtitle indicator on the right that makes navigating the documentation alot easier. This can be subjective, but I show it here so that you might consider updating the website if you agree! 😃 

image
image

**Comment by 2017pxy** [comment]
@yarncraft Thanks for your advice.

Actually, we are planning to improve our docs and we will carefully consider your suggestion from issue or PR (both are OK).  As for adding examples about `get_trainer()` and `get_model()`, we will carefully consider it and choose a proper position to add these examples, and it may takes some time since I am busy in my thesis too. 😄 

About the Furo theme, it indeed looks better and we will consider it as well.

Thanks for your advice again. If I get your authorization, I will close this PR.

**Comment by yarncraft** [comment]
> @yarncraft Thanks for your advice.
> 
> Actually, we are planning to improve our docs and we will carefully consider your suggestion from issue or PR (both are OK). As for adding examples about `get_trainer()` and `get_model()`, we will carefully consider it and choose a proper position to add these examples, and it may takes some time since I am busy in my thesis too. 
> 
> About the Furo theme, it indeed looks better and we will consider it as well.
> 
> Thanks for your advice again. If I get your authorization, I will close this PR.

Thanks, I look forward to future changes! Good luck with your research 😄

**Pull request closed without merging**
