### PR TITLE
Fix argument mismatch error when init dataloader

### PR DESCRIPTION
**Pull request by Tokkiu**
Otherwise, the error will occur when running models in the register table as follows:
Screenshot 2021-04-09 at 1 36 35 AM

### CODE REVIEW

**Comment by 2017pxy** [comment]
@Tokkiu Hi, can you show me your code and config settings when you run these models? Maybe we can check out if here is a bug

**Comment by Tokkiu** [comment]
> @Tokkiu Hi, can you show me your code and config settings when you run these models? Maybe we can check if there is a bug

Yea, to reproduce this issue, just need to run a model in the register table list as follows:
Screenshot 2021-04-10 at 1 22 14 AM (2)

**Comment by 2017pxy** [comment]
@Tokkiu Hi, that is not a bug. If you want to run auto-encode models like CDAE and RecVAE, you need to set `training_neg_sample_num=0` , since these models needn't negative sampling in training phase. By the way, we have already mentioned this point in our docs ([doc for RecVAE](https://recbole.io/docs/user_guide/model/general/recvae.html)) and I suggest you read our docs first when you face problems. Thanks!

**Comment by Tokkiu** [comment]
> @Tokkiu Hi, that is not a bug. If you want to run auto-encode models like CDAE and RecVAE, you need to set `training_neg_sample_num=0` , since these models needn't negative sampling in training phase. By the way, we have already mentioned this point in our docs ([doc for RecVAE](https://recbole.io/docs/user_guide/model/general/recvae.html)) and I suggest you read our docs first when you face problems. We will also improve our error message and make it more clear for users to check out the problems in near future. Thanks!

Thank you for your time! I will delete this pr.

**Pull request closed without merging**
