### PR TITLE
FEA: update overall.config and README

### PR DESCRIPTION
**Pull request by ShanleiMu**

### CODE REVIEW

**Comment by mayaKaplansky** [comment]
Hi
If I want to change parameters in overall.yaml, should I change the original file, or can I copy it to another folder and call it from command line?

**Comment by hyp1231** [comment]
> Hi
> If I want to change parameters in overall.yaml, should I change the original file, or can I copy it to another folder and call it from command line?

This is an old version of RecBole.

In our latest version, we recommend to write all the args you want to customize (including args in ``overall.yaml`` or the other), into another ``.yaml``, which can be fed into ``recbole.quick_start.rec_recbole`` by ``--config_files``.

Please refer to,
https://github.com/RUCAIBox/RecBole/blob/5b0e4a7c4080ce030f561a864bc5095b2403a7a1/run_recbole.py#L18-L25

E.g.
```bash
python run_recbole.py --model=[model_name] --dataset=[dataset_name] --config_files=[config_files_path]
```

**Comment by mayaKaplansky** [comment]
Thanks, is it possible that the download from github did not download the latest version? What command should I use to take the latest one?
I used this: git clone https://github.com/RUCAIBox/RecBole.git && cd RecBole

**Comment by hyp1231** [comment]
> Thanks, is it possible that the download from github did not download the latest version? What command should I use to take the latest one?
> I used this: git clone https://github.com/RUCAIBox/RecBole.git && cd RecBole

Don't worry about the version, your command can work fine.

**Comment by mayaKaplansky** [comment]
Thank you :)

**Pull request merged**
