### PR TITLE
feat: add Random algorithm to GeneralRecommenders

### PR DESCRIPTION
**Pull request by guedes-joaofelipe**
A Random algorithm was added as a General Recommender for baseline purposes. 

The Random algorithm recommends random items for each user. The motivation behind this approach is to create 2 baselines: 

- `Coverage` metric: a random algorithm tends to have a high Item Space Coverage.
- `Ranking`/`Rating` metrics: any recommender algorithm should outperform a random approach in terms o ranking and rating metrics.

The inclusion of the Random class provides easier comparison in terms of the aforementioned metrics

### CODE REVIEW

**Comment by Paitesanshi** [comment]
Thanks for your interest in and contribution to RecBole! I apologize for my delayed response. You are correct that any model should perform better than random. However, I haven't seen any research papers in the field of recommendation systems that use the random method as a baseline for recommendation systems.

**Comment by ChenglongMa** [comment]
Hi @Paitesanshi, I think `random` method could be a good baseline when we want to improve performance like diversity, and coverage other than accuracy-based metrics.

Thanks!

**Comment by guedes-joaofelipe** [comment]
Complementing @ChenglongMa , here is an example of a published paper that explores diversity metrics and uses the Random algorithm as a baseline:

https://dl.acm.org/doi/10.1145/2043932.2043955

**Comment by Paitesanshi** [comment]
@guedes-joaofelipe @ChenglongMa Thank you for pointing that out. You're right. We've now added the Random recommendation algorithm to RecBole's model library. We appreciate your contribution and feedback to the RecBole！

**Pull request merged**
